# Site settings
owner                   : chris_forbes
title                   : Error-Driven Development
description             : To come...
locale                  : en_GB
timezone                : GB

repository              : kitforbes/kitforbes.github.io
url                     : https://kitforbes.github.io
baseurl                 : ''

google_analytics_key    : UA-50156284-3
rss                     : /feed.xml

# Build settings
permalink               : /:categories/:year/:month/:title
lsi                     : true
future                  : false
show_drafts             : false
encoding                : utf-8
markdown                : kramdown
kramdown:
  toc_levels            : 1..3
  input                 : GFM
  hard_wrap             : false
  auto_ids              : true
  entity_output         : as_char
  smart_quotes          : lsquo,rsquo,ldquo,rdquo
  enable_coderay        : false
highlighter             : rouge
keep_files:
  - .git
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - site.bat
  - vendor

# Collections
collections:
  reference:
    output              : true
    permalink           : /:collection/:categories/:title/

# Front matter defaults
defaults:
  -
    scope: # Standard pages
      path              : _pages
      type              : pages
    values:
      layout            : page
      navigation        : true
      comments          : false
  -
    scope: # Intermediate Reference pages
      path              : _pages/reference
      type              : pages
    values:
      layout            : reference-list
      navigation        : false
      comments          : false
  -
    scope: # Blog posts
      path              : _posts/articles
      type              : posts
    values:
      layout            : post
      navigation        : false
      comments          : false
      categories        : Articles
  -
    scope: # Reference collection
      path              : ''
      type              : reference
    values:
      layout            : page
      navigation        : false
      comments          : false
