# Site settings
url                      : http://localhost:4000
show_drafts              : true
unpublished              : true
future                   : true
incremental              : true
profile                  : true
safe                     : true

# Analytics
analytics:
  provider               : false
  google:
    tracking_id          : ''
