# Site settings
title: Christopher Forbes
description: >
  To come...
baseurl: ''
url: https://kitforbes.github.io
#url: http://localhost:4000
repository: kitforbes/kitforbes.github.io
google_analytics_key: UA-50156284-3
social:
  email: kitforbes@gmail.com
  facebook:
  github: kitforbes
  google_plus:
  linkedin:
  rss: feed.xml
  twitter: kitforbes

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - site.bat
  - vendor
include:
  - _pages
