# Site settings
url                      : http://localhost:4000
safe                     : true
incremental              : true

# Analytics
analytics:
  provider               : false
  google:
    tracking_id          : ''
