# Site settings
title: Christopher Forbes
description: >
  To come...
baseurl: ''
url: https://kitforbes.github.io
repository: kitforbes/kitforbes.github.io
permalink: /blog/:year/:month/:title
timezone: GB
google_analytics_key: UA-50156284-3
rss: feed.xml
owner: chris_forbes
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
  - scope:
      path: _pages
      type: pages
    values:
      layout: page

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - site.bat
  - vendor
include:
  - _pages
