# Site settings
url                     : http://localhost:4000

google_analytics_key    : ''

# Build settings
profile                 : true
future                  : true
show_drafts             : true
